package com.gdn.warehouse.assetsmanagement.enums;

public enum AssetStatus {
   NORMAL,
   SCHEDULED_MAINTENANCE,
   PENDING_MAINTENANCE_REQUEST,
   PENDING_MAINTENANCE,
   ON_MAINTENANCE,
   PENDING_TRANSFER,
   ON_TRANSFER,
   ON_TRANSFER_DELIVERY,
   RUSAK_PARAH_SUDAH_BAC,
   RUSAK_PARAH_BELUM_BAC
}
